const SUPABASE_URL = 'https://kzqwxnfcydqmcwyspqob.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6cXd4bmZjeWRxbWN3eXNwcW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1MDYxMzUsImV4cCI6MjA5ODA4MjEzNX0.vNzQVDZxgxLoXDkxAwyUJirL7BdJUM41q2JJfHt6CkE';

window.db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
